# Generated by Django 5.2 on 2025-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_gender_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
