# Generated by Django 5.2 on 2025-06-29 07:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_email_profile_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid phone number.', regex='^(?:\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'created_at'], name='users_otp_user_id_df2d2d_idx'),
        ),
    ]
