# Generated by Django 5.2 on 2025-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_languages_alter_playlists_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
