# Generated by Django 5.2 on 2025-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_rename_section_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
