# Generated by Django 5.2 on 2025-05-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_course_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section',
            new_name='title',
        ),
    ]
