# Generated by Django 5.2 on 2025-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
